version: '3.7'
services:
  nginx:
    image: nginx:alpine-perl
    ports:
      - 80:80
      - 443:443
    networks:
      - backend
    restart: on-failure
    volumes:
      - /usr/mystack/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /usr/mystack/nginx/conf.d:/etc/nginx/conf.d
      - /usr/mystack/nginx/logs.d:/etc/nginx/logs.d
      - /usr/mystack/nginx/cert.d:/etc/nginx/cert.d
      - /usr/mystack/www:/var/www
  php:
    image: php-fpm:alpine
    build:
      context: ./
    restart: on-failure
    depends_on:
      - mariadb
      - memcached
    networks:
      - backend
    volumes:
      - /usr/mystack/php/php.ini:/usr/local/etc/php/php.ini:ro
      - /usr/mystack/www:/var/www
  mariadb:
    image: mariadb:10.4.8
    ports:
      - 127.0.0.1:3306:3306
    networks:
      - backend
    restart: on-failure
    volumes:
      - /usr/mystack/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: cz72sLJtfWYa983nEUIYA
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  memcached:
    image: memcached:alpine
    ports:
      - 127.0.0.1:11211:11211
    networks:
      - backend
    restart: on-failure
  redis:
    image: redis:alpine
    ports:
      - 127.0.0.1:6379:6379
    networks:
      - backend
    restart: on-failure
networks:
  backend: