version: '3.7'
services:
  nginx:
    image: nginx:alpine-brotli
    build:
      context: ./nginx/
    depends_on:
      - php
    ports:
      - 80:80
      - 443:443
    networks:
      - internal
    restart: on-failure
    volumes:
      - /data/mystack/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /data/mystack/nginx/conf.d:/etc/nginx/conf.d
      - /data/mystack/nginx/logs.d:/etc/nginx/logs.d
      - /data/mystack/nginx/cert.d:/etc/nginx/cert.d
      - /data/mystack/www:/var/www
  php:
    image: php-fpm:alpine
    build:
      context: ./php/
    depends_on:
      - mariadb
    networks:
      - internal
    restart: on-failure
    volumes:
      - /data/mystack/php/php.ini:/usr/local/etc/php/php.ini:ro
      - /data/mystack/www:/var/www
  mariadb:
    image: mariadb:alpine
    build:
      context: ./mariadb/
    depends_on:
      - memcached
    ports:
      - 127.0.0.1:3306:3306
    networks:
      - internal
    restart: on-failure
    volumes:
      - myRdsVol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'cz72sLJtfWYa983nEUIYA'
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  memcached:
    image: memcached:alpine
    depends_on:
      - redis
    ports:
      - 127.0.0.1:11211:11211
    networks:
      - internal
    restart: on-failure
  redis:
    image: redis:alpine
    ports:
      - 127.0.0.1:6379:6379
    networks:
      - internal
    restart: on-failure
    volumes:
      - myKvsVol:/data
networks:
  internal:
volumes:
  myRdsVol:
  myKvsVol:
